# Generated by Django 6.0.2 on 2026-03-06 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('card', 'Card'), ('cash', 'Cash on Delivery'), ('bank', 'Bank Transfer')], default='card', max_length=20),
        ),
    ]
